# Generated by Django 4.0 on 2022-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=4000, verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=250, verbose_name='Ответ 1')),
                ('answer2', models.CharField(max_length=250, verbose_name='Ответ 2')),
                ('answer3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 3 (не обязательно)')),
                ('answer4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 4 (не обязательно)')),
                ('answer5', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 5 (не обязательно)')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
