# Generated by Django 4.0 on 2022-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correctAnswer',
            field=models.IntegerField(default=1, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
    ]
