# Generated by Django 4.0 on 2022-02-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_test_answer6_test_answer7'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Query',
        ),
    ]
