# Generated by Django 4.0 on 2022-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_test_query_test_successfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='explanation',
            field=models.TextField(default=1, max_length=2000, verbose_name='объяснение'),
            preserve_default=False,
        ),
    ]
