# Generated by Django 4.0 on 2022-02-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_query_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='employee',
            new_name='employe',
        ),
    ]
