# Generated by Django 4.0 on 2022-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_employee_test_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='company',
        ),
        migrations.RemoveField(
            model_name='test',
            name='employe',
        ),
        migrations.AddField(
            model_name='test',
            name='carModel',
            field=models.CharField(default=1, max_length=100, verbose_name='Модель транспортного средства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='carNumber',
            field=models.CharField(default=1, max_length=100, verbose_name='Гос номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='columnar',
            field=models.CharField(default=1, max_length=100, verbose_name='Kолонный'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='fio',
            field=models.CharField(default=1, max_length=100, verbose_name='Водитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
