# Generated by Django 4.0 on 2022-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_test_company_remove_test_employe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='token',
            field=models.CharField(default=1, help_text='Неповторимий элемент', max_length=100, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
